[versions]
minecraft = "1.18.2"
quilt-mappings = "1.18.2+build.17" # Latest version is available at https://lambdaurora.dev/tools/import_quilt.html
fabric-loader = "0.13.3" # Latest version is available at https://fabricmc.net/versions.html

fabric-api = "0.48.0+1.18.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt-mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }